RallyMVC/Controllers/RallyApiController.cs
using eBayData.DAL;
using Rally.RestApi;
using Rally.RestApi.Json;
using Rally.RestApi.Response;
using RallyMVC.Classes;
using RallyMVC.DAL;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Web.Mvc;
using RallyMVC.ViewModels;
using System.Security.Authentication;
using System.Linq;
using RallyMVC.Filters;

namespace RallyMVC.Controllers
{
    [RallyCredsValidateFilter]
    public class RallyApiController : Controller
    {
        // setup repos
        private readonly IFeatureRepository _featureRepository;
        private readonly IUserStoryRepository _userStoryRepository;
        private readonly IEpicStoryRepository _epicStoryRepository;
        private readonly ITaskRepository _taskRepository;

        public RallyApiController()
        {
            this._featureRepository = new FeatureRepository(new RallyContext());
            this._userStoryRepository = new UserStoryRepository(new RallyContext());
            this._epicStoryRepository = new EpicStoryRepository(new RallyContext());
            this._taskRepository = new TaskRepository(new RallyContext());
        }

        /// <summary>
        /// Main RallyAPI execution page
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
      
        /// <summary>
        /// This is the form that creates the Feature in Rally's API
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Create(int id)
        {
            // get feature
            var feature = _featureRepository.GetFeatureById(id);

            // depending on what Feature Type
            // change page to reflect 
            // textbox and 'search' button to confirm existence of US id entered via AJAX
            // which then enables the 'create in Rally API' button
            
            // build model for display
            UserStoryEpicStoryDisplayViewModel storyModel = new UserStoryEpicStoryDisplayViewModel()
            {
                EpicParentStories = feature.EpicStories,
                StandAloneUserStories = _userStoryRepository.GetUserStoriesByFeatureId(id)
                                                            .Where(x => x.EpicStoryId == null)
                                                            .ToList()
            };
            // create view model
            RallyCreateFeatureViewModel model = new RallyCreateFeatureViewModel()
            {
                FeatureId = id,
                FeatureName = feature.Name,
                FeatureType = feature.FeatureType,
                FeatureTypeId = feature.FeatureTypeId,
                StoryModel = storyModel,
                NewFeatureName = string.Empty,
                NewFeatureNamePrefix = string.Empty
            };

            return View(model);
        }
        
        // ASync Processing/progress bar
        delegate string ProcessTask(RallyCreateFeatureViewModel model);

        // create RallyAPIOperations class instance
        RallyApiOperations rallyObj = new RallyApiOperations();

        /// <summary>
        /// This calls the method to create a new Feature in RallyAPI via
        /// RallyAPIOperations.cs class's 'CreateFeatureInRallyFromDb' method.
        /// The user is again validated to have creds before trying to create.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(RallyCreateFeatureViewModel model)
        {
            // verify this user is setup and has permissions
            AdUserManagement ADum = new AdUserManagement();
            if (!ADum.IsUserSetup())
            {
                throw new AuthenticationException();
            }
            // else try to create in Rally
            try
            {
                // ASync Processing
                rallyObj.Add(model.TaskId);
                ProcessTask processTask = new ProcessTask(rallyObj.CreateFeatureInRallyFromDb);
                processTask.BeginInvoke(model, new AsyncCallback(EndLongRunningProcess), processTask);

                // this is now ASYNC--- XTODOX: do something with this returned reference maybe?
                //var newFeatureReference = rallyObj.CreateFeatureInRallyFromDb(model);

                // send feedback
                TempData["Message"] = "Success: Created New Feature '" + model.NewFeatureName + "' in the RallyAPI. ";

                return RedirectToAction("Index", "Feature");
            }
            catch (Exception ex)
            {
                // log error
                using (ErrorLogger errLogger = new ErrorLogger())
                {
                    errLogger.LogError(ex, User.Identity.Name);
                }
                // send feedback
                TempData["Message"] = "Error: "+
                    "There was a problem creating this feature in the RallyAPI. " +
                    "Have you entered your Rally Credentials and are you 'active'? "+
                    "An Error has been logged in the system.";

                return RedirectToAction("MyRallyCreds", "UserProfile");
            }
        }

        //--------------------------------ASYNC-----------------------------------------------------------------
        /// <summary>
        /// Ends the long running process.
        /// </summary>
        /// <param name="result">The result.</param>
        public void EndLongRunningProcess(IAsyncResult result)
        {
            ProcessTask processTask = (ProcessTask)result.AsyncState;
            string id = processTask.EndInvoke(result);
            rallyObj.Remove(id);
        }

        /// <summary>
        /// Gets the current progress.
        /// </summary>
        /// <param name="id">The id.</param>
        public ContentResult GetCurrentProgress(string id)
        {
            this.ControllerContext.HttpContext.Response.AddHeader("cache-control", "no-cache");
            var currentProgress = rallyObj.GetStatus(id).ToString();
            return Content(currentProgress);
        }
        //--------------------------------------------------------------------------------------------------------
        
        public SelectList GetListOfWorkSpaces()
        {
            // get list from class
            RallyApiOperations rallyObj = new RallyApiOperations();
            var AvailableWorkspaces = rallyObj.GetListOfWorkspaces();
            // assign list from dictionary
            SelectList returnSelectList = new SelectList(AvailableWorkspaces, "Key", "Value", null);

            return returnSelectList;
        }
     
        /// <summary>
        /// This returns available Projects from the RallyAPI for use in a DDL in Epic/UserStory editing.
        /// </summary>
        /// <returns></returns>
        public SelectList GetListOfProjects()
        {
            // get list from class
            RallyApiOperations rallyObj = new RallyApiOperations();
            var AvailableProjects = rallyObj.GetListOfProjects();
            // assign list from dictionary
            SelectList returnSelectList = new SelectList(AvailableProjects, "Key", "Value", null);

            return returnSelectList;
        }

        public SelectList GetListOfAvailableUsers()
        {
            // get list from class
            RallyApiOperations rallyObj = new RallyApiOperations();
            var AvailableProjects = rallyObj.GetAvailableUsers();
            // assign list from dictionary
            SelectList returnSelectList = new SelectList(AvailableProjects, "Key", "Value", null);

            return returnSelectList;
        }

        public SelectList GetListOfPreliminaryEstimates()
        {
            // get list from class
            RallyApiOperations rallyObj = new RallyApiOperations();
            var AvailableProjects = rallyObj.GetListOfPreliminaryEstimates();
            // assign list from dictionary
            SelectList returnSelectList = new SelectList(AvailableProjects, "Key", "Value", null);

            return returnSelectList;
        }

        /// <summary>
        /// This returns a JsonResultViewModel from the RallyAPIController 
        /// </summary>
        /// <param name="FeatureId"></param>
        /// <returns></returns>
        [ValidateAntiForgeryToken]
        public ActionResult GetFeatureReferenceById(string FeatureId)
        {
            // get list from class
            RallyApiOperations rallyObj = new RallyApiOperations();
            var featureReference = rallyObj.GetFeatureReferenceAndNameById(FeatureId);

            return Json(featureReference, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _featureRepository.Dispose();
                _epicStoryRepository.Dispose();
                _userStoryRepository.Dispose();
                _taskRepository.Dispose();
            }
            base.Dispose(disposing);
        }

        // ----TEST METHODS ----

        //public ActionResult CreateTestUserStory()
        //{
        //    RallyApiOperations rallyObj = new RallyApiOperations();
        //    rallyObj.CreateTestUserStory();
        //    return View();
        //}
        //public ActionResult CreateTestPortfolioItem()
        //{
        //    RallyApiOperations rallyObj = new RallyApiOperations();
        //    rallyObj.CreateTestPortfolioItem();
        //    return View();
        //}
        //public ActionResult SAMPLE(int id)
        //{
        //    //string username = "bdmaore@ebay.com";
        //    //string password = "2003Mu5t@ng";
        //    string username = ConfigurationManager.AppSettings["RallyAPIUsername"];
        //    string password = ConfigurationManager.AppSettings["RallyAPIPassword"];

RallyMVC/Views/Feature/Create.cshtml
@model RallyMVC.ViewModels.FeatureCreateViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Feature</h4>
        <hr />
        @Html.ValidationSummary(true, "Some fields are missing!", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.AvailableFeatureTemplateTypes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AvailableFeatureTemplateTypes", Model.AvailableFeatureTemplateTypes, "Choose...", new { @class = "form-control" })
                @Html.ValidationMessage("AvailableFeatureTemplateTypes", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b class="control-label col-md-2">Project</b>
            <div class="col-md-10">
                @Html.DropDownList("RallyProjectId", Model.AvailableProjectsInRally, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <b class="control-label col-md-2">Assigned User</b>
            <div class="col-md-10">
                @Html.DropDownList("AssignedUserId", Model.AvailableUsers, "Choose...", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PreliminaryEstimateChoices, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PreliminaryEstimateId", Model.PreliminaryEstimateChoices, "Choose...", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", style = "width:480px;max-width:480px;" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, 10, 40, new { @class = "form-control", style = "width:480px;max-width:480px;" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.ScheduleStateFeature, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.ScheduleStateFeature, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ScheduleStateFeature, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="createFeatureBtn" value="Create" class="btn btn-success" >
            </div>
        </div>
    </div>
    @Html.Hidden("RallyProjectName")
    @Html.Hidden("PreliminaryEstimateName")
    @Html.Hidden("AssignedUserName")
    @Html.Hidden("AssignedFeatureTemplateTypeId")
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    $(document).ready(function () {

        // onload set the corresponding hidden field value
        $("#RallyProjectName").val($("#RallyProjectId").find("option:selected").text());

        /* 
        on change of DDL's set the corresponding hidden field value
        */
        $("#RallyProjectId").change(function () {
            $("#RallyProjectName").val($(this).find("option:selected").text());
        });
        $("#PreliminaryEstimateId").change(function () {
            $("#PreliminaryEstimateName").val($(this).find("option:selected").text());
        });
        $("#AssignedUserId").change(function () {
            $("#AssignedUserName").val($(this).find("option:selected").text());
        });
        $("#AvailableFeatureTemplateTypes").change(function () {
            $("#AssignedFeatureTemplateTypeId").val($(this).find("option:selected").val());
        });

    });
</script>

RallyMVC/Views/Feature/Delete.cshtml
@model eBayData.Models.Feature

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

@if (ViewBag.Message != null)
{
    <h4 class="alert-warning">@(ViewBag.Message)</h4>
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Feature</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger btn-sm" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RallyMVC/Views/Feature/Index.cshtml
@model IEnumerable<RallyMVC.ViewModels.FeatureListViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Feature Template List</h2>


@Html.ActionLink("Create New Feature Template", "Create", null, null, new { @class = "btn btn-primary btn-sm" , @style = "margin-bottom: 5mm;"})


@if (TempData["Message"] != null) // controller message
{
    <div class="alert alert-info fade in" role="alert" id="MessageAlert">
        <strong>@(TempData["Message"])</strong>
    </div>
    <script>
        // fade out/slideup in 3 seconds
        $("#MessageAlert").fadeTo(3000, 500).slideUp(500, function () {
            $("#MessageAlert").alert('close');
        });
    </script>
}

<table class="table table-hover table-striped">

    @foreach (var group in Model.GroupBy(m => m.FeatureTemplateType).OrderBy(x => x.Key)) // top-down
    {
        <tr>
            <td colspan="5" class="text-center featureTypeTitle">@group.Key <i>Template(s)</i></td>
        </tr>
        <tr style="font-size: 10pt; line-height: 10px;">
            <th width="30%">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th width="60%">
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>Edit</th>
            <th>Remove</th>
            <th></th>
        </tr>
        foreach (var item in group)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td align="center">
                    <span class="divGlyphicon"><a href="@Url.Action("Edit", new { id = item.Id })"><span class="glyphicon glyphicon-edit" title="Edit @(item.Name)"></span></a></span>
                </td>
                <td align="center">
                    <span class="divGlyphicon"><a href="@Url.Action("Delete", new { id = item.Id })"><span class="glyphicon glyphicon-remove" title="Remove @(item.Name)"></span></a></span>
                </td>
                <td width="20%" nowrap align="center">                    
                    @if (item.CanCreateInRally)
                    {
                        @Html.ActionLink("Create In Rally", "Create", "RallyApi", new { id = item.Id }, new { @class = "btn btn-success btn-sm", title = "Create Template " + item.Name })
                    }
                    else
                    {
                        <a href="@Url.Action("Edit", new { id = item.Id })">
                            <span class="btn btn-warning" title="Edit this Template">Incomplete</span>
                        </a>
                    }
                </td>
            </tr>
        }
    }

</table>