RallyMVC/Controllers/FeatureController.cs
using eBayData.DAL;
using eBayData.Models;
using RallyMVC.Classes;
using RallyMVC.DAL;
using RallyMVC.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using RallyMVC.Filters;

namespace RallyMVC.Controllers
{
    //[RallyCredsValidateFilter]
    public class FeatureController : Controller
    {
        // setup repos
        private readonly IFeatureRepository _featureRepository;
        private readonly IFeatureTypeRepository _featureTypeRepository;
        private readonly IEpicStoryRepository _epicStoryRepository;
        private readonly IUserStoryRepository _userStoryRepository;
        private readonly ITaskRepository _taskRepository;
        private readonly IUserProfileRepository _userProfileRepository;
        // for PreliminaryEstimates (HARD CODED)
        private readonly List<SelectListItem> _preliminaryEstimates = SimpleObjects.PreliminaryEstimateItems();

        public FeatureController()
        {
            // init repos
            this._featureRepository = new FeatureRepository(new RallyContext());
            this._featureTypeRepository = new FeatureTypeRepository(new RallyContext());
            this._epicStoryRepository = new EpicStoryRepository(new RallyContext());
            this._userStoryRepository = new UserStoryRepository(new RallyContext());
            this._taskRepository = new TaskRepository(new RallyContext());
            this._userProfileRepository = new UserProfileRepository(new RallyContext());
        }

        /// <summary>
        /// This gets the list of Features that have at least one Task in any Story below it.
        /// We can change this later as Sue mentioned that Tasks might not be mandatory in some instances
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            List<FeatureListViewModel> model = _featureRepository.GetFeatures()
                .Select(x => new FeatureListViewModel()
                {
                    Id = x.Id,
                    Name = x.Name,
                    Description = x.Description,
                    FeatureTemplateType = x.FeatureType.Name, // for grouping by feature name
                    CanCreateInRally = x.EpicStories.Any(y => y.UserStories.Any(z => z.Tasks.Count > 0))
                                    || x.UserStories.Any(a => a.Tasks.Count > 0) //<- only true if feature has at least 1 Task in User/Epic story
                })
                .ToList();

            return View(model);
        }

        // GET: Feature/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        /// <summary>
        /// Must get and back the AvailableProjects from the RallyAPI
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            // must plass model for UIHint to work even if blank
            FeatureCreateViewModel model = new FeatureCreateViewModel();

            // get available Projects from RallyAPI
            RallyApiOperations rallyObj = new RallyApiOperations();
            var availableProjects = rallyObj.GetListOfProjects();

            // fill in model
            model.AvailableProjectsInRally = availableProjects;
            model.PreliminaryEstimateChoices = _preliminaryEstimates;

            // dropdown
            model.AvailableUsers = _userProfileRepository.GetUserProfiles()
             .Select(x => new SelectListItem()
             {
                 Text = x.FullName,
                 Value = x.Id.ToString()
             }).ToList();

            // dropdown
            model.AvailableFeatureTemplateTypes = _featureTypeRepository.GetFeatureTypes()
                .Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });

            return View(model);
        }

        /// <summary>
        /// Creates the feature, simple.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [RallyCredsValidateFilter]
        [HttpPost]
        public ActionResult Create(FeatureCreateViewModel model)
        {
            Feature f = new Feature()
            {
                FeatureTypeId = model.AssignedFeatureTemplateTypeId,
                Name = model.Name,
                Description = model.Description,
                RallyProjectId = model.RallyProjectId,
                RallyProjectName = model.RallyProjectName,
                PreliminaryEstimateName = model.PreliminaryEstimateName,
                PreliminaryEstimateId = model.PreliminaryEstimateId,
                UserProfileId = model.AssignedUserId
            };
            _featureRepository.InsertFeature(f);
            _featureRepository.Save();

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Gets the feature for editing
        /// </summary>
        /// <param name="id"></param> is the FeatureId
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            //RallyApiOperations rallyObj = new RallyApiOperations();
            //var availableProjects = rallyObj.GetListOfProjects();
            var availableProjects = new List<SelectListItem>
            {
                new SelectListItem()
                {
                    Value = "123", Text = "Project Name"
                }
            };

            var feature = _featureRepository.GetFeatureById(id);

            FeatureEditViewModel model = new FeatureEditViewModel
            {
                AvailableProjectsInRally = availableProjects,               // available projects (Rally-side)
                Description = feature.Description,                          // particulars
                Id = feature.Id,
                Name = feature.Name,
                UserStories = feature.UserStories.ToList(),
                RallyProjectId = feature.RallyProjectId,                    // Project info
                RallyProjectName = feature.RallyProjectName,
                PreliminaryEstimateChoices = _preliminaryEstimates,         // Preliminary Estimate
                PreliminaryEstimateId = feature.PreliminaryEstimateId,
                PreliminaryEstimateName = feature.PreliminaryEstimateName,
                AssignedUserId = feature.UserProfileId ?? 0,                // assigned user
                AvailableUsers = _userProfileRepository.GetUserProfiles()   // available users
                    .Select(x => new SelectListItem()
                    {
                        Text = x.FullName,
                        Value = x.Id.ToString()
                    }).ToList(),
                AssignedFeatureTemplateTypeId = feature.FeatureTypeId,
                AvailableFeatureTemplateTypes = _featureTypeRepository.GetFeatureTypes() // available Feature Types
                    .Select(x => new SelectListItem()
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    }).ToList()
            };

            return View(model);
        }

        /// <summary>
        /// This method Edits/updates the Feature
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(FeatureEditViewModel model)
        {
            //try
            //{
            // get feature
            Feature f = _featureRepository.GetFeatureById(model.Id);
            // update feature
            f.Name = model.Name;
            f.Description = model.Description;
            f.RallyProjectId = model.RallyProjectId;
            f.RallyProjectName = model.RallyProjectName;
            f.FeatureTypeId = model.AssignedFeatureTemplateTypeId;
            // preliminary estimate
            f.PreliminaryEstimateId = model.PreliminaryEstimateId;
            f.PreliminaryEstimateName = !string.IsNullOrEmpty(model.PreliminaryEstimateId) ? model.PreliminaryEstimateName : null;
            // assigned user
            f.UserProfileId = model.AssignedUserId;
            // tell repo
            _featureRepository.UpdateFeature(f);
            _featureRepository.Save();
            // send feedback
            TempData["Message"] = "Success: Updated this Feature.";

            return RedirectToAction("Edit", new
            {
                ID = model.Id
            });
            //}
            //catch
            //{
            //    // send feedback
            //    TempData["Message"] = "Failed Updating this Feature.";
            //    return RedirectToAction("Edit", new
            //    {
            //        ID = model.Id
            //    });
            //}
        }

        // GET: Feature/Delete/5
        public ActionResult Delete(int id)
        {
            var model = _featureRepository.GetFeatureById(id);
            return View(model);
        }

        // POST: Feature/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            //try
            //{
            _featureRepository.DeleteFeature(id);
            _featureRepository.Save();

            return RedirectToAction("Index");
            //}
            //catch (Exception ex)
            //{
            //    ViewBag.Message = ex.InnerException;
            //    return View();
            //}
        }

        public ActionResult SortItems(SortItemsViewModel model)
        {
            // return model
            GenericJsonViewModel returnModel = new GenericJsonViewModel();
            returnModel.Result = 0;

            // what type of sort?
            switch (model.SortUpdateType)
            {
                case "EpicStory":
                    // get the ALL epic stories for this Epic's FeatureId

RallyMVC/Controllers/HelpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RallyMVC.Controllers
{
    public class HelpController : Controller
    {
        // GET: Help
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit()
        {
            return View();
        }

        public ActionResult EditDetails()
        {
            return View();
        }

        public ActionResult UsageInRally()
        {
            return View();
        }

    }
}

RallyMVC/Views/Help/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Help - <i>Create New Template</i></h2>

<h4 class="helpHeaderH4">Step 1: Click 'Create New Template'</h4>

<p>
    To create a new Template, click the <a href="@(Url.Action("Create","Feature"))" class="btn btn-primary btn-sm text-center">Create New Feature Template</a> 
    button on the home page or on the <a href="@(Url.Action("Index","Feature"))">'Feature Templates'</a> link in the top menu.
    You will be presented with a form with some required fields to get the basic info for the new feature.
</p>

<h4 class="helpHeaderH4">Step 2: Fill out Basic Info</h4>

<p>
    Choose a 'Template Type', 'Name', and 'Description' 
    at minimum. 
<p/>
<p>
    'Template Type' is a choice of 'New Feature' or 'Update Existing Feature'. The difference is 'New Feature' simply creates a new Feature in Rally
    and 'Update Existing Feature' will update an existing feature in Rally.
    After filling it out, click 'Create'.
</p>

<div class="helpImgDiv">
    <span class="helpImgTitle">Create New Feature Form</span><br />
    <img class="helpImg" src="~/Content/Images/form-createnewfeature.JPG" />
</div>

<p>You will then be taken directly to the Feature List.</p>

<a href="@(Url.Action("Edit","Help"))" class="helpNavLink">Go to 'Edit Template' Help<div class="glyphicon glyphicon-chevron-right"></div></a> 

RallyMVC/Views/Help/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<h2>Help - <i>Edit Template</i></h2>

<h4 class="helpHeaderH4">Step 1: Getting to the Edit Screen</h4>

<p>
    To edit an existing Template or one you just created, click on <a href="@(Url.Action("Index", "Feature"))">Feature Templates</a> in the menu.
    You will see a list like this one:
</p>
<div class="helpImgDiv">
    <span class="helpImgTitle">Feature Template List</span><br />
    <img class="helpImg" src="~/Content/Images/feature-template-list.JPG" />
</div>

<p>
    You can click<span class="glyphicon glyphicon-edit"></span> to Edit,<span class="glyphicon glyphicon-remove"></span> to remove,
    or <img src="~/Content/Images/btncreateinRallyBig.JPG" alt="Create In Rally" /> (if available). 
</p>
<p>
    Create In Rally is only available if a template has at least one task otherwise it will be marked <span class="btn btn-warning">Incomplete</span>.
</p>
<hr />

<h4 class="helpHeaderH4">Step 2: When you click 'Edit' on one of the Templates</h4>

<p>
    The top of this page is the same 'Basic Info' that can be edited and saved. From 'Details' down are the Epic/User stories and associated tasks.
</p>

<div class="helpImgDiv">
    <span class="helpImgTitle">Edit Basic Info Form</span><br />
    <img class="helpImg" src="~/Content/Images/feature-template-edit.JPG" />
</div>

<a href="@(Url.Action("EditDetails","Help"))" class="helpNavLink">Go to 'Edit Template Details' Help<div class="glyphicon glyphicon-chevron-right"></div></a> 

RallyMVC/Views/Help/EditDetails.cshtml
@{
    ViewBag.Title = "EditDetails";
}

<h2>Help - <i>Edit Template Details</i></h2>

<h4 class="helpHeaderH4">Understanding this screen</h4>
<p>
    In the Details section, when interacting with any Feature Template,
    you will be shown various *<b>modal</b> windows that 'pop-up', to allow editing
    of every facet. 
</p>
<p>
    You can also sort items so that they are created in Rally in the
    same priority as you see them in the template.
</p>
<p>
    <i style="font-size:10pt; font-weight: bold;">
        * Each modal form has required fields.
        You will be informed if there are any fields missing that require data entry.
    </i>
</p>


<h4 class="helpHeaderH4">Interacting with the Template</h4>
<h5>Adding Epic and Stand-Alone Stories</h5>

<p>    
    If you click either <img src="~/Content/Images/btn-add-epic-story.JPG" />
    or <img src="~/Content/Images/btn-add-stand-alone-user-story.JPG" />
    you will be presented with a generic form for both Epic and User Stories. 
    This form has required fields, as well.
    @*<a href="@(Url.Action("Index", "Feature"))">Feature Templates</a>*@ 
</p>
<div class="helpImgDiv">
    <span class="helpImgTitle">Add User Story Form</span><br />
    <img class="helpImg" src="~/Content/Images/modal-epicuser-stories.JPG" />
</div>


<hr />
<h5>Adding User Stories To Epics</h5>
<p>
    You can add User Stories to Epic Stories by clicking the 'Add User Story to ...' button
    under each Epic Story.
</p>
<div class="helpImgDiv">
    <span class="helpImgTitle">Add User Story To Epic Story Modal</span><br />
    <img class="helpImg" src="~/Content/Images/help-add-user-story-to-epic.JPG" />
</div>
<p>
    Which will show you another modal like this.
</p>
<div class="helpImgDiv">
    <span class="helpImgTitle">Add/Update Epic/User Story Modal</span><br />
    <img class="helpImg" src="~/Content/Images/help-add-user-story-modal.JPG" />
</div>


<hr />
<h5>Adding Tasks To User Stories</h5>
<p>
    You can add Tasks to User Stories by clicking the 'Add Task to ...' button
    under each User Story.
</p>
<div class="helpImgDiv">
    <span class="helpImgTitle">Add User Story To Epic Story Modal</span><br />
    <img class="helpImg" src="~/Content/Images/help-add-task-to-userstory-modal.JPG" />
</div>
<p>
    Which will show you another modal like this.
</p>
<div class="helpImgDiv">
    <span class="helpImgTitle">AddTask to User Story Modal</span><br />
    <img class="helpImg" src="~/Content/Images/help-add-task-modal.JPG" />
</div>


<hr />
<h5>Editing Tasks and Stories</h5>
<p>
    You can edit Tasks and Stories by clicking icons for <span class="glyphicon glyphicon-edit"></span> Edit
    &nbsp;&nbsp; or <span class="glyphicon glyphicon-remove"></span> Remove &nbsp;&nbsp;next to each respective item.
    A modal will show with the existing information that you can edit and save.
</p>
<div class="helpImgDiv">
    <span class="helpImgTitle">Edit User Story Modal</span><br />
    <img class="helpImg" src="~/Content/Images/help-edit-story-modal.JPG" />
</div>



<h4 class="helpHeaderH4">Sorting Items</h4>
<h5 class="helpStrongInfoH5">--Sorting is among siblings in the same container only.--</h5>

<p>
    When you have more than one of anything,
    you can sort their creation order in Rally by dragging/dropping above and below their siblings.
</p>
<p>
    However, you <b>cannot</b>, for example, <i>drag a task from one User Story to another User/Epic Story</i>.
    Nor can you <i>drag a UserStory from one Epic to another Epic</i>.
</p>
<div class="helpImgDiv">
    <span class="helpImgTitle">Before Sort</span><br />
    <img class="helpImg" src="~/Content/Images/help-sort-before.JPG" />
</div>
<hr />
<div class="helpImgDiv">
    <span class="helpImgTitle">During Sort</span><br />
    <img class="helpImg" src="~/Content/Images/help-sort-during.JPG" />
</div>
<hr />
<div class="helpImgDiv">
    <span class="helpImgTitle">After Sort</span><br />
    <img class="helpImg" src="~/Content/Images/help-sort-after.JPG" />
</div>

<a href="@(Url.Action("UsageInRally","Help"))" class="helpNavLink">Go to 'Usage In Rally' Help<div class="glyphicon glyphicon-chevron-right"></div></a> 

RallyMVC/Views/Help/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Help</h2>

<div class="helpListDiv">
    <div>        
        <p>
            <div class="glyphicon glyphicon-question-sign"></div>
            Here are the help pages for each step in the process.
        </p>
    </div>
    <ul class="list-unstyled helpListUL">
        <li class="li1"><span class="glyphicon glyphicon-pencil">&nbsp;</span><a href="@(Url.Action("Create"))">How to Create a new Template</a></li>
        <li class="li2"><span class="glyphicon glyphicon-edit">&nbsp;</span><a href="@(Url.Action("Edit"))">How to Edit an existing Template</a> </li>
        <li class="li1"><span class="glyphicon glyphicon-list-alt">&nbsp;</span><a href="@(Url.Action("EditDetails"))">How to Edit the Details of an existing Template</a> </li>
        <li class="li2"><span class="glyphicon glyphicon-transfer">&nbsp;</span><a href="@(Url.Action("UsageInRally"))">Usage in Rally</a> </li>
    </ul>    
</div>

RallyMVC/Views/Help/UsageInRally.cshtml
@{
    ViewBag.Title = "UsageInRally";
}

<h4 class="helpHeaderH4">Template Usage in Rally</h4>
<p>
    When moving to create/apply your template to Rally, you will need to supply different information depending on the <b>Template Type</b>.
</p>
<p>
    Currently, there are two <b>Template Types</b>:
    <ul>
        <li style="margin-bottom:20px;">
            <b class="bg-warning">New Feature</b> - <i>requires a name</i> and an optional 'prefix' that will prefix your Feature as well as all your Stories, Tasks, etc. If you leave 'prefix' blank it will be ignored
            <ul>
                <li>Enter a Prefix <i>(Optional)</i></li>
                <li>
                    Enter a Name <i>(Required)</i>
                    <br />

                    <div class="helpImgDiv">
                        <span class="helpImgTitle">Create New Feature</span><br />
                        <img class="helpImg" src="~/Content/Images/CreateNewFeature.JPG" />
                    </div>

                </li>
            </ul>
        </li>
        <li>
            <b class="bg-warning">Update Existing Feature</b> - <i>requires the lookup</i> of an existing 'Feature Id' <i><b>(leading 'F' is optional in Id)</b></i>
            <ul>
                <li>Enter an Id<br />
                    <div class="helpImgDiv">
                        <span class="helpImgTitle">Existing Feature Lookup in Rally</span><br />
                        <img class="helpImg" src="~/Content/Images/LookUpFeatureId.JPG" alt="Existing Feature Lookup in Rally" />
                    </div></li>
                <li>Click 'Lookup Feature Id'
                    <div class="helpImgDiv">
                        <span class="helpImgTitle">Looking Up</span><br />
                        <img class="helpImg" src="~/Content/Images/LookingUpFeatureId.JPG" alt="Looking Up" />
                    </div></li>
                <li>On Success
                    <div class="helpImgDiv">
                        <span class="helpImgTitle">Success</span><br />
                        <img class="helpImg" src="~/Content/Images/LookUpSucceededFeatureId.JPG" alt="Success" />
                    </div></li>
                <li>On Fail
                    <div class="helpImgDiv">
                        <span class="helpImgTitle">Failure</span><br />
                        <img class="helpImg" src="~/Content/Images/LookUpFailedFeatureId.JPG" alt="Failure" />
                    </div></li>
            </ul>
        </li>
        </ul>

        <p>
            <b class="">Upon attempting to CREATE any template in Rally, you will be presented a progress bar. <br />Simply wait until it completes.</b>
            <ul>
                <li><div class="helpImgDiv">
                        <span class="helpImgTitle">Progress Bar</span><br />
                        <img class="helpImg" src="~/Content/Images/RallyProgressBar.JPG" />
                    </div></li>
            </ul>
        </p>
</p>